package sank.xbook.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sank.xbook.database.Books;
import sank.xbook.database.Chapters;
import sank.xbook.database.HistoryRecord;

import sank.xbook.database.greendao.BooksDao;
import sank.xbook.database.greendao.ChaptersDao;
import sank.xbook.database.greendao.HistoryRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig booksDaoConfig;
    private final DaoConfig chaptersDaoConfig;
    private final DaoConfig historyRecordDaoConfig;

    private final BooksDao booksDao;
    private final ChaptersDao chaptersDao;
    private final HistoryRecordDao historyRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        booksDaoConfig = daoConfigMap.get(BooksDao.class).clone();
        booksDaoConfig.initIdentityScope(type);

        chaptersDaoConfig = daoConfigMap.get(ChaptersDao.class).clone();
        chaptersDaoConfig.initIdentityScope(type);

        historyRecordDaoConfig = daoConfigMap.get(HistoryRecordDao.class).clone();
        historyRecordDaoConfig.initIdentityScope(type);

        booksDao = new BooksDao(booksDaoConfig, this);
        chaptersDao = new ChaptersDao(chaptersDaoConfig, this);
        historyRecordDao = new HistoryRecordDao(historyRecordDaoConfig, this);

        registerDao(Books.class, booksDao);
        registerDao(Chapters.class, chaptersDao);
        registerDao(HistoryRecord.class, historyRecordDao);
    }
    
    public void clear() {
        booksDaoConfig.clearIdentityScope();
        chaptersDaoConfig.clearIdentityScope();
        historyRecordDaoConfig.clearIdentityScope();
    }

    public BooksDao getBooksDao() {
        return booksDao;
    }

    public ChaptersDao getChaptersDao() {
        return chaptersDao;
    }

    public HistoryRecordDao getHistoryRecordDao() {
        return historyRecordDao;
    }

}
