package sank.xbook.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import sank.xbook.database.HistoryRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_RECORD".
*/
public class HistoryRecordDao extends AbstractDao<HistoryRecord, Long> {

    public static final String TABLENAME = "HISTORY_RECORD";

    /**
     * Properties of entity HistoryRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Time = new Property(1, String.class, "time", false, "TIME");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
        public final static Property BookName = new Property(3, String.class, "bookName", false, "BOOK_NAME");
        public final static Property BookAuthor = new Property(4, String.class, "bookAuthor", false, "BOOK_AUTHOR");
        public final static Property BookType = new Property(5, String.class, "bookType", false, "BOOK_TYPE");
        public final static Property BookSynopsis = new Property(6, String.class, "bookSynopsis", false, "BOOK_SYNOPSIS");
        public final static Property BookUpdateTime = new Property(7, String.class, "bookUpdateTime", false, "BOOK_UPDATE_TIME");
    }


    public HistoryRecordDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TIME\" TEXT," + // 1: time
                "\"IMAGE\" TEXT," + // 2: image
                "\"BOOK_NAME\" TEXT," + // 3: bookName
                "\"BOOK_AUTHOR\" TEXT," + // 4: bookAuthor
                "\"BOOK_TYPE\" TEXT," + // 5: bookType
                "\"BOOK_SYNOPSIS\" TEXT," + // 6: bookSynopsis
                "\"BOOK_UPDATE_TIME\" TEXT);"); // 7: bookUpdateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistoryRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(4, bookName);
        }
 
        String bookAuthor = entity.getBookAuthor();
        if (bookAuthor != null) {
            stmt.bindString(5, bookAuthor);
        }
 
        String bookType = entity.getBookType();
        if (bookType != null) {
            stmt.bindString(6, bookType);
        }
 
        String bookSynopsis = entity.getBookSynopsis();
        if (bookSynopsis != null) {
            stmt.bindString(7, bookSynopsis);
        }
 
        String bookUpdateTime = entity.getBookUpdateTime();
        if (bookUpdateTime != null) {
            stmt.bindString(8, bookUpdateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistoryRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(4, bookName);
        }
 
        String bookAuthor = entity.getBookAuthor();
        if (bookAuthor != null) {
            stmt.bindString(5, bookAuthor);
        }
 
        String bookType = entity.getBookType();
        if (bookType != null) {
            stmt.bindString(6, bookType);
        }
 
        String bookSynopsis = entity.getBookSynopsis();
        if (bookSynopsis != null) {
            stmt.bindString(7, bookSynopsis);
        }
 
        String bookUpdateTime = entity.getBookUpdateTime();
        if (bookUpdateTime != null) {
            stmt.bindString(8, bookUpdateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HistoryRecord readEntity(Cursor cursor, int offset) {
        HistoryRecord entity = new HistoryRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // image
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bookName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bookAuthor
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bookType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bookSynopsis
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // bookUpdateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistoryRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBookName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBookAuthor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBookType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBookSynopsis(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBookUpdateTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HistoryRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HistoryRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HistoryRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
